spring:
  application:
    name: gridcapa-core-valid-d2-post-processing
  cloud:
    function:
      definition: consumeTaskDtoUpdate

core-valid-d2-post-processing:
  process:
    tag: CORE_VALID_D2
    timezone: CET